#! /usr/bin/env bash
# hyakvnc - A script to launch VNC sessions on Hyak

# shellcheck disable=SC2292
[ -n "${XDEBUG:-}" ] && set -x # Set XDEBUG to print commands as they are executed
# shellcheck disable=SC2292
[ -n "${BASH_VERSION:-}" ] || { echo "Requires Bash"; exit 1; }
set -o pipefail # Use last non-zero exit code in a pipeline
set -o errtrace # Ensure the error trap handler is inherited
set -o nounset  # Exit if an unset variable is used

SCRIPTDIR="${BASH_SOURCE[0]%/*}/scripts"
# shellcheck source=scripts/_lib.bash
source "${SCRIPTDIR}/_lib.bash"

function main() {
	local action
	local orig_args=()
	orig_args+=("${@:-}")

	action=help
	while true; do
		case "${1:-}" in
			-d | --debug) # Debug mode
				set_log_level DEBUG
				shift
				;;
			--log-level) # Set log level
				[[ -n "${2:-}" ]] || { log ERROR "$1 requires a non-empty option argument"; exit 1; }
				shift
				set_log_level "$1"
				shift
				;;
			-h | --help)
				shift
				action=help
				;;
			-V | --version)
				echo "HyakVNC version ${HYAKVNC_VERSION:-}"
				exit 0
				;;
			*) action="${1:-}"
			break
				;;
		esac
	done

	if [[ -r "${SCRIPTDIR}/${action:=help}.bash" ]]; then
		shift
	else
		log ERROR "Unknown command: \"${action:-}\""
		echo
		"${SCRIPTDIR}/help.bash" -u
		exit 1
	fi

	case "${action}" in
		help | install | update | config)
			hyakvnc_config_init || log WARN "Could't initialize config automatically" # Don't exit if config can't be initialized (e.g., not running on SLURM)
			;;
		*)
			hyakvnc_config_init || exit 1                                 # Fill in default values for config variables or exit if config can't be initialized
			hyakvnc_autoupdate "${orig_args:-}" || log TRACE "Didn't autoupdate" # Don't exit if didn't autoupdate
			;;
	esac

	[[ -n "${!HYAKVNC_@}" ]] && export "${!HYAKVNC_@}" # Export all HYAKVNC_ variables
	[[ -n "${!SBATCH_@}" ]] && export "${!SBATCH_@}" # Export all SBATCH_ variables
	[[ -n "${!SLURM_@}" ]] && export "${!SLURM_@}" # Export all SLURM_ variables

	exec "${SCRIPTDIR}/${action}.bash" "$@"
}

# shellcheck disable=SC2046

[[ -n "${!HYAKVNC_@}"  ]] && export "${!HYAKVNC_@}" # Export all HYAKVNC_ variables
[[ -n "${!SBATCH_@}"  ]] && export "${!SBATCH_@}" # Export all SBATCH_ variables
[[ -n "${!SLURM_@}"  ]] && export "${!SLURM_@}" # Export all SLURM_ variables

main "$@"
