#! /usr/bin/env bash
# hyakvnc - A script to launch VNC sessions on Hyak
set -EuT -o pipefail
shopt -qs lastpipe
shopt -qs inherit_errexit


SCRIPTPATH="$(readlink -f "${BASH_SOURCE[0]}")"
SCRIPTDIR="$(dirname "${SCRIPTPATH}")"

SCRIPTDIR=${BASH_SOURCE[0]%/*}
# shellcheck source=_lib.bash
source "${SCRIPTDIR}/_lib.bash"

case "${XDEBUG:-0}" in 1|t*|T*|y*|Y*) export PS4='${BASH_SOURCE[0]##*/}:${LINENO} : '; set -x ;; *) ;; esac

function main() {
	local action=help
  local actionfn
	local -a orig_args=()
	orig_args+=("${@:-}")

	while (($# > 0)); do
		case "${1:-}" in
			-d | --debug) # Debug mode
				set_log_level DEBUG || { log ERROR "Couldn't set log level to DEBUG"; return 1; }
				;;
			--log-level) # Set log level
				shift || { log ERROR "$1 requires an argument"; return 1; }
				set_log_level "$1" || { log ERROR "Couldn't set log level to \"$1\""; return 1; }
				;;
			-h | --help)
				action=help
				;;
			-m | --module)
				shift || { log ERROR "$1 requires an argument"; return 1; }
				export HYAKVNC_MODULE="$1"
				;;
			-V | --version)
				echo "HyakVNC version ${HYAKVNC_VERSION:-}"
				exit 0
				;;
			help | create | show | list | stop | config | update)
				action="$1"
				;;
			*)  # Unknown option
				log   ERROR "Unknown option: \"$1\""
				return   1
				;;
		esac
		shift
	done
	hyakvnc_init "${orig_args[@]}" || { log ERROR "Couldn't initialize HyakVNC"; return 1; }
	hyakvnc_command "${action:-}" "${@:-}" || { log ERROR "Couldn't run command: \"${action:-}\""; return 1; }
}

main "$@"
