name: Build installer
"on":
  push:

jobs:
  build-readme:
    runs-on: ubuntu-latest
    name: Build install.sh
    permissions: write-all
    steps:
      - name: Install jinja-cli
        run: |
          python3 -m pip install jinja-cli
      - name: Check out code for the container build
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check if install.j2.sh has changed
        id: installer-changed
        run: |
          if git --no-pager diff --name-only --quiet --diff-filter=AM ${{ github.event.before }} ${{ github.event.after }} -- .build/install.j2.sh .github/workflows/mkinstaller.yml; then
            gh run cancel ${{ github.run_id }}
            gh run watch ${{ github.run_id }}
          fi
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create and push install.sh
        run: |
          jinja -D j2_hyakvnc_repo_url 'https://github.com/${{ github.repository }}' -o install.sh .build/install.sh.j2
          git config --local user.email "${{ github.event.sender.id }}+${{ github.event.sender.login }}@users.noreply.github.com"
          git config --local user.name ${{ github.event.sender.login }}
          git add install.sh
          git commit -am "Update install.sh"
          git push

